### ISSUE TITLE
Support For Iteration

### ISSUE THREAD

**Issue by quicknir** [krabicezpapundeklu/smart_enum#1]
Hi, very nice library. I'm curious, do you have an appetite for adding support for iteration? I would suggest supporting two syntaxes:

```
using e1_traits = smart_enum::enum_traits<e_1>;

std::for_each(e1_traits.begin(), e1_traits.end(), ...);

for ( auto e : e1_traits::range() ) { 
...
}
```

range() would just return a trivial object with begin and end methods. Obviously doing this properly is a bit of work (need cbegin and rbegin variants ideally)

**Comment by krabicezpapundeklu** [comment]
Please, see  `examples_iterators` and `examples_range` functions in `examples.cpp`. Do you have any comments or is it fine? (I didn't update documentation yet.)

**Comment by quicknir** [comment]
Awesome stuff, I must have missed it. I will sit down with it in more depth at some point in the next couple of weeks but overall it looks terrific.
