### ISSUE TITLE
To/from string support

### ISSUE THREAD

**Issue by quicknir** [krabicezpapundeklu/smart_enum#2]
There's a couple of related points here. First, it would be good to have some kind of conversion function that goes from string to an enum. Second, a couple of thoughts on the to-string interface, currently given by description. The name: could description be changed to something more idiomatic like to_string? Also, this is possibly related: what's the use case for allowing a description different from the name of the enum? Since the name of the enum doesn't actually affect the code at all, it seems like this adds more complexity and potential confusion for little benefit. The only application I see is to handle either "scoped" or unscoped names, but this could be handled by a trait or different to_string functions (or booleans).

**Comment by krabicezpapundeklu** [comment]
Thanks for your feedback!
I added `from_string` and `to_string` methods (see `dev` branch, I plan to merge it in few days).
Yeah, you are right with `description`. It was a little bit too "clever" and I probably wouldn't use this functionality anyway.

**Comment by quicknir** [comment]
Cool stuff! This is great timing for me, I was looking for something like this. I evaluated a few libraries, but they were all much more invasive and doing things in non-optimal ways for better backwards compatibility (e.g. typesafe enums for C++03). I was basically resigned to doing things myself from scratch, but this is fantastic, looking forward to digging into the implementation.

**Comment by krabicezpapundeklu** [comment]
I merged `dev` into `master`. There are also "shortcut" methods you can use, for example:

``` c++
from_string<e_1>("e_1_a") = e_1::e_1_a; // converts value name to value
to_string(e_1::e_1_a) = "e_1_a" // converts value to string
```
