### ISSUE TITLE
constexpr error

### ISSUE THREAD

**Issue by quicknir** [krabicezpapundeklu/smart_enum#3]
It seems that from_string is marked constexpr, and uses std::strcmp, which is not constexpr. Am I missing something?

**Comment by krabicezpapundeklu** [comment]
Ah, thanks for catching it! That's bug. Fixed now.
(For discussion why I changed it to `strcmp` see this [reddit](https://www.reddit.com/r/cpp/comments/40i6i0/tiny_library_for_c_smart_enum_introspection/cyxqlsz)).
