### ISSUE TITLE
Usage inside namespaces/structs

### ISSUE THREAD

**Issue by quicknir** [krabicezpapundeklu/smart_enum#4]
Hello,

Unfortunately, it seems like the current approach cannot play nice with declaring an enum inside a namespace or struct. The reason being is that there is no way to do the template specialization of the traits class while nested in that namespace. Since most enums (like all things) are declared within a namespace, this seems like major issue.

The preferred solution, IMHO (and the only clean way to get it to work with structs) is to replace the proper templated traits struct, with a simple identified based struct. So instead of generating an enum/enum class called e_1, and a specialization of smart_enum::enum_traits<e_1>, you would instead just generate a struct e_1_traits. It can still inherit from the templated base to gain some of the functionality. I've tried changing some things in the macros to make this change; I don't think it's that hard but it's not trivial either.

What do you think? It's less elegant, but IMHO much more practical.

Other than that it looks fantastic, I took it for a spin today and it works perfectly.

**Comment by quicknir** [comment]
Actually, let me take my suggested solution back: it unfortunately would make it very hard to use the enums in any generic setting. So instead, I suggest the following: the macro can only be used at global scope, but you can pass namespaces in so that you can qualify the namespace of the enum. I think that some boost libraries (e.g. Fusion) already do things like this, DECLARE_STRUCT( (ns1)(ns2)(struct_name), ....) or something like that.

To use it in a struct, I guess I'll live with declaring the enum in a detail namespace and then adding a using declaration.

**Comment by krabicezpapundeklu** [comment]
Good idea! I'll take a look this week.

**Comment by krabicezpapundeklu** [comment]
OK, please, see commit [59019f6](https://github.com/krabicezpapundeklu/smart_enum/commit/59019f6bfb1dcddb7daf81ee6a845fc27a520d47). There is a lot of mess I need to clean and I'm not even sure if it compiles with g++/clang :-/

**Comment by krabicezpapundeklu** [comment]
For enums within structs/classes something like this may work:

``` c++
struct aaa
{
    enum class x : short;
};

SMART_ENUM_CLASS((aaa::x, short), (a, b, c))
```

**Comment by quicknir** [comment]
Cool and thanks! I'll test this out shortly.

**Comment by krabicezpapundeklu** [comment]
Hm, [59019f6](https://github.com/krabicezpapundeklu/smart_enum/commit/59019f6bfb1dcddb7daf81ee6a845fc27a520d47) doesn't work well with clang/g++.
I'm working on some [clean-up](https://github.com/krabicezpapundeklu/smart_enum/tree/clean-up) and will reimplement it there. Then it should work fine.

**Comment by krabicezpapundeklu** [comment]
Merged into `master` (I will update readme in few days).
You can use something like this:

```
SMART_ENUM(n_1, e_1, ...) // namespace n_1 { enum e_1 {...
SMART_ENUM((n_1, n_2), e_2, ...) //namespace n_1 { namespace n_2 { enum e_2 {...
```
